### PR TITLE
[WIP] Add multiple track support

### PR DESCRIPTION
**Pull request by eh-steve**
Addresses https://github.com/alexandrainst/alexandra-trackmap-panel/issues/13

This is a bit of a major refactor to support multiple time series being returned. It also adds support for:

* Custom SVG Markers for different timeseries by label value
* Custom AntPath colours for different timeseries by label value
* Custom map tile URLs (+ access token + domains)
* Concept of a "non-live" track, where lat/lon data is null for the latest timestamp, but exists within the panel's time window.
* Paused AntPath for "non-live" tracks
* Only show markers for "live" tracks

@Alkarex I would appreciate opinions on whether this is a direction worth pursuing?

This is an example of what you can do with the new configuration options using custom tile layers and custom marker overrides using time series label values
image

### CODE REVIEW

**Comment by Alkarex** [comment]
@eh-steve That looks very good already 👍🏻 Go ahead!
Could you please write if you can think of any back-compatibility issue?

**Comment by JorundMartinsen** [comment]
Very good with the new options, especially the custom tileserver url.

Could you update the documentation to include the new and updated options?

**Comment by ZhongyuWang** [comment]
Dear @eh-steve 

Could you please guide me how to test the pull request. The markers disappear in your version but works fine in the original version. I have also tried to change the "Default marker HTML" option with no luck. The first image is the original version and the second is the new version with exactly the same settings.

origin
pr51

Best regards,
Zhongyu

**Comment by DmitrySidorow** [comment]
Hello! Thank you for that great update! But I have same problem as @ZhongyuWang. My markers are disappears. My datasource is Portgres 12 + timescaledb 2.2.1

**Comment by eh-steve** [comment]
Have you tried selecting as time series rather than table?

**Comment by DmitrySidorow** [comment]
> Have you tried formatting as time series rather than table?

Table and time series does not work

**Comment by eh-steve** [comment]
Hmmm... I just set up a dummy postgres/timescaleDB table with this data:
image
and set up the panel with defaults (except I enabled `Map center to first position`, and formatted the results as time series) and it seems to work:

image

Can you post a table schema and data which reproduces the problem?

**Comment by DmitrySidorow** [comment]
> Hmmm... I just set up a dummy postgres/timescaleDB table with this data:
> image
> and set up the panel with defaults (except I enabled `Map center to first position`, and formatted the results as time series) and it seems to work:
> 
> image
> 
> Can you post a table schema and data which reproduces the problem?

It worked for me when I put a number in the tooltip, not a string. Is it possible to make support formatting as a table?

**Comment by xkilian** [comment]
@eh-steve Does the plugin support mapping the tooltip to string (value mapping). If it doesn't would it be possible to add it in, it will increase the flexibility and reduce the amount of questions/support. 👍🏼

**Comment by eh-steve** [comment]
> @eh-steve Does the plugin support mapping the tooltip to string (value mapping). If it doesn't would it be possible to add it in, it will increase the flexibility and reduce the amount of questions/support. 👍🏼

I think it should as long as the the field name of `popup` or `text` or `desc` is used for popups, and `tooltip` for tooltips (though I haven't tested these).

**Comment by eh-steve** [comment]
> Is it possible to make support formatting as a table?
Supporting both table and timeseries for multiple tracks would require duplicating a bit of functionality as the data is structured differently. Is there a particular use case you had which can't be addressed via timeseries?

**Comment by DmitrySidorow** [comment]
> > Is it possible to make support formatting as a table?
> 
> Supporting both table and timeseries for multiple tracks would require duplicating a bit of functionality as the data is structured differently. Is there a particular use case you had which can't be addressed via timeseries?

I cannot use string values with time series formatting.
image

**Comment by smilingface7117** [comment]
Tried this plugin with influsDB as data source and grafana 7.5.9. Cannot see any Markers on the map.

**Query:**
SELECT mean("latitude") AS "lat", mean("longitude") AS "long" FROM "autogen"."influxmqtt_consumer" WHERE ("topic" = 'kpi-data') AND time >= now() - 5m GROUP BY time(200ms) fill(none)

** Table**
image

**Comment by DmitrySidorow** [comment]
@eh-steve 
Hey, how is the progress going? I can't wait for the update :)

**Comment by oliver0513** [comment]
Hi,

plugin work great with Grafana 7.5.10 but i can't use "Custom SVG Markers for different timeseries" by label value option. My Query is from MySQL DB. How do you override label ?

thx

**Comment by j-or** [comment]
Multi-query support would be a great addition! I've done some work on this refactor, mainly focusing on multi-track support. I've re-added some functionality that was removed/overwritten and fixed some things that seemed to no longer work, like heatmaps. Using html for icons is now a toggle in case someone wants to use the original version with pngs. Custom tile server has already been added via another PR. I haven't had time to look into the live-track functionality, so that is currently commented out. I might add an issue for this if I don't get it done. The "discard zero or null" feature no longer works after support for multi-track, so that needs works too. 

It would be great if someone could test the newest version - @eh-steve @oliver0513 @DmitrySidorow @JorundMartinsen @xkilian @smilingface7117 ? Note that currently, the tracks must either be timeseries or table, not a mix (though this could probably be added in a future update).

**Comment by DmitrySidorow** [comment]
> Multi-query support would be a great addition! I've done some work on this refactor, mainly focusing on multi-track support. I've re-added some functionality that was removed/overwritten and fixed some things that seemed to no longer work, like heatmaps. Using html for icons is now a toggle in case someone wants to use the original version with pngs. Custom tile server has already been added via another PR. I haven't had time to look into the live-track functionality, so that is currently commented out. I might add an issue for this if I don't get it done. The "discard zero or null" feature no longer works after support for multi-track, so that needs works too.
> 
> It would be great if someone could test the newest version - @eh-steve @oliver0513 @DmitrySidorow @JorundMartinsen @xkilian @smilingface7117 ? Note that currently, the tracks must either be timeseries or table, not a mix (though this could probably be added in a future update).

thank you! now it works with timeseries. But tooltip has wrong position.
image

**Comment by oliver0513** [comment]
Hi all,

@j-or  tested on grafana 8.1.1 windows OS with mutiple query from sql database, it work fine now except for html markers but I think it is rather me who made a configuration error. Can you provide a sample ?

thx

image
image

**Comment by DmitrySidorow** [comment]
image
I think we need option to manually adjust the tooltip position

**Pull request merged**
